Grid overblikk
navikt/veilarbdetaljerfs pull request #11
Opened 2023-06-26 13:10 UTC by SanneEdlandsommerstudent

Samme skjedde igjen med ekstra commits, kun den siste som tells til denne PRen

2023-06-26 13:26 UTC, JulieHillRoa requested changes

2023-06-26 13:26 UTC, JulieHillRoa commented on src/components/overblikk.tsx
> +      hentTolk('10108000398').then(data => {
Kan denne sendes inn som en variabel? :)

2023-06-26 13:26 UTC, JulieHillRoa commented on src/components/overblikk.tsx
> +        <div>
#nitpick, men litt formatering hadde gjort seg her :D

2023-06-26 13:26 UTC, JulieHillRoa commented on src/components/overblikk.tsx
> +        <div>
Kan se ut som at 
```
  <div>
        <h3></h3>
        <p></p>
   </div>
```
potensielt kan trekkes ut som en egen komponent? :) 
Ville kanskje vurdert å kjøre noe annet enn h3 forsåvidt, kanskje heller se på det som en slags descriptionlist (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dt) eller liknende? :)

2023-06-26 13:32 UTC, JulieHillRoa requested changes

2023-06-26 13:32 UTC, JulieHillRoa commented on src/components/overblikk.css
> +div > h3 {
Potensielt litt skummelt å ikke være mer presis i css'en når kodebasen er en del av et større bilde - detaljer er jo kun en mikrofrontend sammen med flere apper. burde nok derfor altså legge det i no css klasse eller si at det kun skal gjelde innenfor en klasse man definerer på body nivå om ikke annet (så det kun skjer i detaljer og ikke også i andre apper. Dersom personflate har en footer f.eks vil denne kunne "cascade" nedover sant). Dersom dette ble rotete kan du bare ta kontakt.

2023-06-28 09:37 UTC, slovrid approved these changes

2023-06-29 12:57 UTC, JulieHillRoa approved these changes

2023-07-05 10:31 UTC, closed without merging