Lagt til ikoner og brukt komponenter
navikt/veilarbdetaljerfs pull request #66
Opened 2023-07-26 07:32 UTC by SanneEdlandsommerstudent

- Lagt til ikoner på alle headings som skal ha ikon
- Brukt komponenter istedenfor vanlig <panel> hvor det kan brukes
- Endret CSS til komponentbibliotek istedenfor vanlig css

2023-07-26 07:46 UTC, slovrid commented
Et eller annet rart som skjer med dette ikonet her:
![Screenshot 2023-07-26 at 09 46 34](https://github.com/navikt/veilarbdetaljerfs/assets/111113539/af088416-eb2a-4887-a3db-31d9838c08a5)

2023-07-26 07:56 UTC, Mathiamu commented on src/components/registrering/registrering.css
> +    padding: var(--a-spacing-4) var(--a-spacing-2) var(--a-spacing-4) var(--a-spacing-2);
```suggestion
    padding: var(--a-spacing-4) var(--a-spacing-2);
```

2023-07-26 07:56 UTC, Mathiamu commented on src/components/personalia/fullmakt.tsx
>          <div>
Denne `<div>`-en kan nok tas bort 🤔

2023-07-26 08:07 UTC, SanneEdlandsommerstudent commented
> Et eller annet rart som skjer med dette ikonet her:
> ![Screenshot 2023-07-26 at 09 46 34](https://user-images.githubusercontent.com/111113539/256155956-af088416-eb2a-4887-a3db-31d9838c08a5.png)

Denne feilen skjer ikke hos meg? Kan dere se på ny? :O

2023-07-26 08:33 UTC, slovrid commented
> > Et eller annet rart som skjer med dette ikonet her:
> > ![Screenshot 2023-07-26 at 09 46 34](https://user-images.githubusercontent.com/111113539/256155956-af088416-eb2a-4887-a3db-31d9838c08a5.png)
> 
> Denne feilen skjer ikke hos meg? Kan dere se på ny? :O

Nå forsvant det 🤷

2023-07-26 08:41 UTC, slovrid commented
Etter å ha lest litt i Aksel om bruk av Ikoner så er det to ting jeg tror vi kan forbedre:

* bruke `aria-hidden=true`, siden disse ikonene bare er "til pynt", ref. [`aria-hidden` (aksel.nav.no)]((https://aksel.nav.no/god-praksis/artikler/tilgjengelig-ikonbruk#h01b547f8a11c))
* spesifisere en tittel til ikonet vha. `title`-propen, da jeg tror det er god praksis å gjøre dette selv om vi har markert ikonet som "pynt", ref: [`aria-labelledby` og `title` (aksel.nav.no)](https://aksel.nav.no/god-praksis/artikler/tilgjengelig-ikonbruk#h8fc3c3d73c92)

2023-07-26 08:44 UTC, slovrid commented on src/components/ytelserinfo.tsx
> +                            <EnkeltInformasjon header={'Aktivitetsfase'} value={vedtak.aktivitetsfase || EMDASH} />
```suggestion
                            <EnkeltInformasjon header="Aktivitetsfase" value={vedtak.aktivitetsfase || EMDASH} />
```

2023-07-26 08:45 UTC, slovrid commented on src/components/ytelserinfo.tsx
> +                                header="Fradato / Tildato"
Er "Fradato"/"Tildato" lovlig skrivemåte? Jeg hadde kanskje tenkt at det var "Fra dato / til dato", eventuelt bare "Fra / til dato" 🤔

2023-07-26 09:05 UTC, slovrid requested changes
Se kommentarer

2023-07-27 06:24 UTC, slovrid commented on src/App.tsx
> +                            Gi tilbakemeldinger i Forms <ExternalLinkIcon title="a11y-title" aria-hidden="true" />
`a11y-title` må byttes med en beskrivende tittel (antar dette bare er en placeholder) - gjelder flere steder i koden 😄

2023-07-27 06:26 UTC, slovrid requested changes
Se siste kommentar

2023-07-28 10:22 UTC, slovrid approved these changes

2023-07-28 10:23 UTC, merged